const types = {
  RESTAURANT: 'restaurant',
  FOOD: 'food',
  BEVERAGE: 'beverage',
};

const companies = [
  {
    id: 'comp0',
    name: 'Meet',
    type: types.RESTAURANT,
  },
];

const categories = [
  {
    id: 'cat0',
    name: 'Förrätter',
    type: types.FOOD,
  },
  {
    id: 'cat1',
    name: 'Huvudrätter',
    type: types.FOOD,
  },
  {
    id: 'cat2',
    name: 'Efterrätter',
    type: types.FOOD,
  },
  {
    id: 'cat3',
    name: 'Tillbehör',
    type: types.FOOD,
  },
  {
    id: 'cat4',
    name: 'Öl',
    type: types.BEVERAGE,
  },
  {
    id: 'cat5',
    name: 'Bubbel & Vin',
    type: types.BEVERAGE,
  },
  {
    id: 'cat6',
    name: 'Cider',
    type: types.BEVERAGE,
  },
  {
    id: 'cat7',
    name: 'Grogg',
    type: types.BEVERAGE,
  },
  {
    id: 'cat8',
    name: 'Alkoholfritt',
    type: types.BEVERAGE,
  },
];

const variants = [
  {
    name: 'Varianter',
    id: 'i0',
    isMultiSelect: false,
    items: [
      {
        name: 'Rare',
        price: 0,
        id: 'v0',
      },
      {
        name: 'Medium',
        price: 0,
        id: 'v1',
      },
      {
        name: 'Well done',
        price: 0,
        id: 'v2',
      },
    ],
  },
  {
    name: 'Extra',
    id: 'i1',
    isMultiSelect: true,
    items: [
      {
        id: 'e1',
        name: 'Extra potatismos',
        price: 15,
      },
      {
        id: 'e2',
        name: 'Extra köttbullar',
        price: 25,
      },
      {
        id: 'e3',
        name: 'Extra sylt',
        price: 10,
      },
    ],
  },
  {
    name: 'Tillägg',
    id: 'i2',
    isMultiSelect: true,
    items: [
      {
        id: 'a1',
        name: 'Brunsås',
        price: 8,
      },
      {
        id: 'a2',
        name: 'Bearnaise',
        price: 8,
      },
    ],
  },
];

const items = [
  {
    id: 'i0',
    category: 'cat0',
    name: 'Ostron med tillbehör',
    price: 175,
    currency: 'kr',
    upSell: 'cat3',
    inStock: true,
    description: 'Citron, Tabasco, Schalottenlök',
    diet: 'Blötdjur',
    img:
      'https://images.unsplash.com/photo-1578882422378-9ed72be08b5e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1479&q=80',
  },
  {
    id: 'i1',
    category: 'cat0',
    name: 'Karl-Johan Svampravioli',
    price: 155,
    currency: 'kr',
    upSell: 'cat3',
    inStock: true,
    description:
      'Gruyèreskum, Hasselnötter, Brynt smör, Svampfyllda pasta',
    diet: 'Nötter, Svamp',
    img: '',
  },
  {
    id: 'i2',
    category: 'cat1',
    name: 'Ryggbiff',
    price: 225,
    currency: 'kr',
    upSell: 'cat3',
    inStock: true,
    description:
      'Jordärtskocka, Bondbönor, Trattkantareller, Päron, Rödvinssås',
    diet: 'Kött, Svamp',
    img:
      'https://images.unsplash.com/photo-1556269923-e4ef51d69638?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1571&q=80',
    variants: [variants[0]],
  },
  {
    id: 'i3',
    category: 'cat1',
    name: 'Köttbullar med potatismos',
    price: 165,
    currency: 'kr',
    upSell: 'cat3',
    inStock: true,
    description: 'Rårörda lingon, Inlagd gurka',
    diet: 'Kött',
    img:
      'https://images.unsplash.com/photo-1529042410759-befb1204b468?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=933&q=80',
    variants: [variants[1], variants[2]],
  },
  {
    id: 'i4',
    category: 'cat1',
    name: 'Fisksoppa från Västerhavet',
    price: 225,
    currency: 'kr',
    upSell: 'cat3',
    inStock: true,
    description:
      'Musslor, Räkor, Torsk, Lax, Citron, Kumminaioli, Krutonger',
    diet: 'Blötdjur, Fisk',
    img: '',
  },
  {
    id: 'i5',
    category: 'cat2',
    name: 'En kula citronsorbet',
    price: 55,
    currency: 'kr',
    upSell: 'cat4',
    inStock: true,
    description: 'Citron',
    diet: 'Sorbet',
    img:
      'https://images.unsplash.com/photo-1531361396412-58ba6481bfe4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=975&q=80',
  },
  {
    id: 'i6',
    category: 'cat2',
    name: 'Smördegsbakat vinteräpple',
    price: 105,
    currency: 'kr',
    upSell: 'cat4',
    inStock: true,
    description:
      'Citron & Kardemummacrème, Mandelmassa, Rosmarinkolasås',
    diet: 'Smördeg',
    img: '',
  },
  {
    id: 'i7',
    category: 'cat3',
    name: 'Pommes Frites',
    price: 45,
    currency: 'kr',
    inStock: true,
    description: 'Pommes',
    diet: 'Potatis',
    img:
      'https://images.unsplash.com/photo-1484009902830-a314db11070c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80',
  },
  {
    id: 'i8',
    category: 'cat3',
    name: 'Bearnaise',
    price: 15,
    currency: 'kr',
    inStock: true,
    description: 'Bearnaise',
    diet: 'Sås',
    img: '',
  },
  {
    id: 'i9',
    category: 'cat3',
    name: 'BBQ Sås',
    price: 15,
    currency: 'kr',
    inStock: true,
    description: 'BBQ',
    diet: 'Sås',
    img: '',
  },
  {
    id: 'i10',
    category: 'cat4',
    name: 'Heineken',
    price: 55,
    currency: 'kr',
    inStock: true,
    description: 'Öl',
    diet: 'Öl',
    img:
      'https://images.unsplash.com/photo-1516128043650-037fbdbd0b6e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80',
  },
  {
    id: 'i11',
    category: 'cat4',
    name: 'Carlsberg',
    price: 45,
    currency: 'kr',
    inStock: true,
    description: 'Öl',
    diet: 'Öl',
    img: '',
  },
  {
    id: 'i12',
    category: 'cat5',
    name: 'Chablis AOC',
    price: 139, //'139/599'
    currency: 'kr',
    inStock: true,
    description: 'Vitt vin',
    diet: 'Vin',
    img:
      'https://images.unsplash.com/photo-1503436298338-2adbc8a8e006?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80',
  },
  {
    id: 'i13',
    category: 'cat5',
    name: 'Zonin Valpolicella Ripasso Superiore',
    price: 139, //'139/599'
    currency: 'kr',
    inStock: true,
    description: 'Rött vin',
    diet: 'Vin',
    img: '',
  },
  {
    id: 'i14',
    category: 'cat5',
    name: 'Domaine Houchart Cotes De Provence',
    price: 99, //'99/399'
    currency: 'kr',
    inStock: true,
    description: 'Rött vin',
    diet: 'Vin',
    img: '',
  },
  {
    id: 'i15',
    category: 'cat5',
    name: 'A Viot Brut Tradition',
    price: 129, //'129/499'
    currency: 'kr',
    inStock: true,
    description: 'Champagne',
    diet: 'Champagne',
    img: '',
  },
  {
    id: 'i16',
    category: 'cat6',
    name: 'Somersby Äpple',
    price: 45,
    currency: 'kr',
    inStock: true,
    description: 'Cider',
    diet: 'Cider',
    img: '',
  },
  {
    id: 'i17',
    category: 'cat6',
    name: 'Somersby Päron',
    price: 45,
    currency: 'kr',
    inStock: true,
    description: 'Cider',
    diet: 'Cider',
    img: '',
  },
  {
    id: 'i18',
    category: 'cat7',
    name: 'Gin & Tonic',
    price: 125,
    currency: 'kr',
    inStock: true,
    description: 'Grogg',
    diet: 'Grogg',
    img: '',
  },
  {
    id: 'i19',
    category: 'cat7',
    name: 'Rom & Cola',
    price: 125,
    currency: 'kr',
    inStock: true,
    description: 'Grogg',
    diet: 'Grogg',
    img: '',
  },
  {
    id: 'i20',
    category: 'cat8',
    name: 'Fanta',
    price: 15,
    currency: 'kr',
    inStock: true,
    description: 'Alkoholfritt',
    diet: 'Alkoholfritt',
    img: '',
  },
  {
    id: 'i21',
    category: 'cat8',
    name: 'Coca cola',
    price: 15,
    currency: 'kr',
    inStock: true,
    description: 'Alkoholfritt',
    diet: 'Alkoholfritt',
    img: '',
  },
  {
    id: 'i22',
    category: 'cat1',
    name: 'Grillad Flankstek',
    price: 275,
    currency: 'kr',
    upSell: 'cat3',
    inStock: true,
    description:
      'Panzanella, Chimichurri, Majsaioli, Pommes',
    diet: 'Kött, Grönsaker',
    img:
      'https://imgs.aftonbladet-cdn.se/v2/images/e3bee90e-6743-470d-b9e0-a966d3874115?fit=crop&h=733&q=50&w=1100&s=7eb4a10e28dd6df3874d71c38362f6628832780c',
    variants: [variants[0], variants[2]],
  },
  {
    id: 'i23',
    category: 'cat1',
    name: 'Grillad Lammfilé',
    price: 275,
    currency: 'kr',
    upSell: 'cat3',
    inStock: true,
    description:
      'Frasig sötpotatis, Rökt tomat, Vinägersky, Getostkräm',
    diet: 'Kött, Laktos',
    img:
      'https://assets.icanet.se/q_auto,f_auto/imagevaultfiles/id_92847/cf_259/ortdressad-lammfile-med-citron-och-vitlok-717536.png',
    variants: [variants[0], variants[2]],
  },
  {
    id: 'i24',
    category: 'cat1',
    name: 'Tryffel- och Svamprisotto',
    price: 255,
    currency: 'kr',
    upSell: 'cat3',
    inStock: true,
    description:
      'Grillad king oyster svamp, arborioris, solrospesto, körsbärstomat, parmesan',
    diet: 'Grönsaker, Svamp, Laktos',
    img:
      'https://static.mathem.se/shared/images/recipes/doublelarge/tryffelrisotto_sannalivijnwexell.jpeg',
    variants: [variants[2]],
  },
  {
    id: 'i25',
    category: 'cat0',
    name: 'Toast Skagen',
    price: 155,
    currency: 'kr',
    upSell: 'cat8',
    inStock: true,
    description:
      'Handskalade räkor, rödlök, pepparrot, dill, surdegsbröd',
    diet: 'Skaldjur, Grönsaker, Gluten',
    img:
      'https://cdn1.tasteline.com/Toast-Skagen2-med-lojrom-pa-grillat-surdegsbrod-foto-Nurlan-Emir-Mathem.jpg',
  },
  {
    id: 'i26',
    category: 'cat0',
    name: 'Västerbotten Kroketter',
    price: 155,
    currency: 'kr',
    upSell: 'cat8',
    inStock: true,
    description:
      'Handskalade räkor, rödlök, pepparrot, dill, surdegsbröd',
    diet: 'Skaldjur, Grönsaker, Gluten',
    img:
      'https://wp.kit.se/app/uploads/2016/08/1470052529-79a290ac3eb95c0ebc2e09d47da1f454.jpg',
  },
  {
    id: 'i27',
    category: 'cat0',
    name: 'Löjrom',
    price: 155,
    currency: 'kr',
    upSell: 'cat8',
    inStock: true,
    description: 'Brioche, rödlök, smetana, citron',
    diet: 'Fisk, Grönsaker',
    img:
      'https://www.landleyskok.se/wp-content/uploads/2015/12/blinier_IMG_6035-main.jpg',
  },
  {
    id: 'i28',
    category: 'cat2',
    name: 'Chokladbavaroise',
    price: 115,
    currency: 'kr',
    upSell: 'cat4',
    inStock: true,
    description:
      'Hasselnöts nougat, havtorn, salt choklad karamell',
    diet: 'Nötter, Laktos, Bär',
    img:
      'https://cdn1.tasteline.com/Mjolkchokladbavaroise-med-bananpytt-original.jpg',
  },
  {
    id: 'i29',
    category: 'cat2',
    name: 'Crème brûlée',
    price: 105,
    currency: 'kr',
    upSell: 'cat5',
    inStock: true,
    description: 'Vanilj, havtorn, havrecrumble',
    diet: 'Bär',
    img:
      'https://www.livewellbakeoften.com/wp-content/uploads/2019/02/Homemade-Creme-Brulee-9.jpg',
  },
  {
    id: 'i30',
    category: 'cat2',
    name: 'Vaniljglass',
    price: 55,
    currency: 'kr',
    upSell: 'cat8',
    inStock: true,
    description: 'Karamellsås, vit choklad',
    diet: 'Laktos',
    img:
      'https://mittkok.expressen.se/wp-content/uploads/2015/07/fotolia_107832514_subscription_monthly_m-1-700x700.jpg',
  },
  {
    id: 'i31',
    category: 'cat3',
    name: 'Rostade nötter',
    price: 47,
    currency: 'kr',
    inStock: true,
    description: 'Cashew, mandel, jordnöt, valnöt',
    diet: 'Nötter',
    img:
      'https://cdn-rdb.arla.com/Files/arla-se/3792701366/44a9894f-1d22-4578-9154-1c0bac0f138d.jpg?mode=crop&w=479&h=335&ak=f525e733&hm=d7d1b1dd',
  },
  {
    id: 'i32',
    category: 'cat3',
    name: 'Oliver',
    price: 40,
    currency: 'kr',
    inStock: true,
    description: 'Oliver',
    diet: 'Oliver',
    img:
      'https://www.thespruceeats.com/thmb/ojAOG-0ZY7TGBjB5Qb_5Ju3PBr4=/1500x1500/smart/filters:no_upscale()/Greekolives-GettyImages-87114126-598b34640d327a0011750e06.jpg',
  },
  {
    id: 'i33',
    category: 'cat4',
    name: 'Mariestads',
    price: 55,
    currency: 'kr',
    inStock: true,
    description: 'Öl',
    diet: 'Öl',
    img: '',
  },
  {
    id: 'i34',
    category: 'cat4',
    name: 'Norrlands Guld',
    price: 45,
    currency: 'kr',
    inStock: true,
    description: 'Öl',
    diet: 'Öl',
    img: '',
  },
  {
    id: 'i35',
    category: 'cat6',
    name: 'Briska Päroncider',
    price: 55,
    currency: 'kr',
    inStock: true,
    description: 'Cider',
    diet: 'Cider',
    img: '',
  },
  {
    id: 'i36',
    category: 'cat6',
    name: 'Cult Apricot',
    price: 35,
    currency: 'kr',
    inStock: true,
    description: 'Cider',
    diet: 'Cider',
    img: '',
  },
  {
    id: 'i37',
    category: 'cat7',
    name: 'Mojito',
    price: 115,
    currency: 'kr',
    inStock: true,
    description: 'Grogg',
    diet: 'Grogg',
    img: '',
  },
  {
    id: 'i38',
    category: 'cat7',
    name: 'Old Fashioned',
    price: 115,
    currency: 'kr',
    inStock: true,
    description: 'Grogg',
    diet: 'Grogg',
    img:
      'https://www.liquor.com/thmb/lavmUGaMMriZPSxfHsPnyK15bSY=/720x720/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__liquor__2018__05__08113350__bourbon-old-fashioned-720x720-recipe-ade6f7780c304999be3577e565c9bcdd.jpg',
  },
  {
    id: 'i39',
    category: 'cat8',
    name: 'Sprite',
    price: 15,
    currency: 'kr',
    inStock: true,
    description: 'Alkoholfritt',
    diet: 'Alkoholfritt',
    img: '',
  },
  {
    id: 'i40',
    category: 'cat8',
    name: 'Ramlösa',
    price: 15,
    currency: 'kr',
    inStock: true,
    description: 'Alkoholfritt',
    diet: 'Alkoholfritt',
    img: '',
  },
];

const receipts = [
  {
    id: 'i0',
    companyId: 'comp0',
    userId: 'user0',
    date: 1585302840660,
    content:
      '<!DOCTYPE html><html><meta name="viewport" content="width=device-width, initial-scale=1"><head><style>hr.dashed{border:0.5px dashed #424242}p{font-size:small;margin:0}p.subTitle{text-align:center}h2{text-align:center}</style></head><body><div><h2>Meet</h2><p class="subTitle">Adressgatan 1, 414 14 Göteborg</p><p class="subTitle">Orgnr: 12345678</p><p class="subTitle">Datum: 2020-04-08 22:28</p><hr class="dashed"><div style="overflow: hidden;"><p style="float: left;">1x Ryggbiff</p><p style="float: right;">300.00 kr</p></div><div style="overflow: hidden;"><p style="float: left;">2x Fanta</p><p style="float: right;">100.00 kr</p></div><hr class="dashed"><div style="overflow: hidden;"><p style="float: left;">Totalt</p><p style="float: right;">400.00 kr</p></div><div style="overflow: hidden;"><p style="float: left;">Moms 25%</p><p style="float: right;">160.80 kr</p></div><p>Betald med swish</p></div></body></html>',
  },
  {
    id: 'i1',
    companyId: 'comp0',
    userId: 'user0',
    date: 1585302840660,
    content:
      '<!DOCTYPE html><html><meta name="viewport" content="width=device-width, initial-scale=1"><head><style>hr.dashed{border:0.5px dashed #424242}p{font-size:small;margin:0}p.subTitle{text-align:center}h2{text-align:center}</style></head><body><div><h2>Meet</h2><p class="subTitle">Adressgatan 1, 414 14 Göteborg</p><p class="subTitle">Orgnr: 12345678</p><p class="subTitle">Datum: 2020-04-08 22:28</p><hr class="dashed"><div style="overflow: hidden;"><p style="float: left;">1x Ryggbiff</p><p style="float: right;">300.00 kr</p></div><div style="overflow: hidden;"><p style="float: left;">2x Fanta</p><p style="float: right;">100.00 kr</p></div><hr class="dashed"><div style="overflow: hidden;"><p style="float: left;">Totalt</p><p style="float: right;">400.00 kr</p></div><div style="overflow: hidden;"><p style="float: left;">Moms 25%</p><p style="float: right;">160.80 kr</p></div><p>Betald med swish</p></div></body></html>',
  },
];

const order_details = [];

/**
 * REVIEWS TABLE:
 * The date property is set to Date.now() here just to get a timestamp.
 * In a real scenario the Date.now() should be set on the client side when the review is posted.
 *
 * The user property is a property set by the user via an input, not fetched from the user ID.
 * The user should have the possibility to remain anonymous.
 */

const reviews = [
  {
    id: 0,
    item: items[0],
    rating: 1.0,
    comment: 'It was bad',
    date: Date.now(),
    user: 'Ali',
    company: companies[0],
  },
  {
    id: 1,
    item: items[1],
    rating: 3.0,
    comment: 'It was alright',
    date: Date.now(),
    user: 'Kevin',
    company: companies[0],
  },
  {
    id: 2,
    item: items[2],
    rating: 3.0,
    comment: 'It was alright',
    date: Date.now(),
    user: 'Michael',
    company: companies[0],
  },
  {
    id: 3,
    item: items[2],
    rating: 4.5,
    comment: 'It was good',
    date: Date.now(),
    user: 'Andreas',
    company: companies[0],
  },
  {
    id: 4,
    item: items[2],
    rating: 5,
    comment: 'It was very good',
    date: Date.now(),
    user: 'Ebba',
    company: companies[0],
  },
  {
    id: 5,
    item: items[2],
    rating: 1,
    comment: 'It was not good',
    date: Date.now(),
    user: 'Putte',
    company: companies[0],
  },
];

export default {
  categories,
  companies,
  items,
  types,
  receipts,
  order_details,
  reviews,
};
